# This is a config for E2B sandbox template.
# You can use template ID (7sm3qma8pv1uukuldbvq) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("7sm3qma8pv1uukuldbvq") # Sync sandbox
# sandbox = await AsyncSandbox.create("7sm3qma8pv1uukuldbvq") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('7sm3qma8pv1uukuldbvq')

team_id = "e4d57c24-f999-47e3-ae67-35736f22e8ba"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "grills_template"
template_id = "7sm3qma8pv1uukuldbvq"
