# This is a config for E2B sandbox template.
# You can use template ID (hnh6yl8ejhv6y03c5vml) or template name (grills-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("grills-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("grills-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('grills-template')

team_id = "e4d57c24-f999-47e3-ae67-35736f22e8ba"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "grills-template"
template_id = "hnh6yl8ejhv6y03c5vml"
